import React, { useState, useEffect } from "react";

const QAApp = () => {
  const [results, setResults] = useState([]);

  useEffect(() => {
    // In a real scenario, this might fetch from a JSON file generated by check-integrity.sh
    fetch("/root/EPICOS_CERTIFICATION.json")
      .then(res => res.json())
      .then(data => setResults(data.tests))
      .catch(e => console.log("Certification not found yet"));
  }, []);

  return (
    <div className="p-8 bg-zinc-950 min-h-screen text-white font-mono">
      <h1 className="text-3xl font-bold text-red-600 mb-8 border-b border-red-900 pb-2">
        EpicOS Certification Suite
      </h1>
      <div className="space-y-4">
        {results.map((t, i) => (
          <div key={i} className="flex justify-between items-center p-4 border border-zinc-800 rounded bg-zinc-900">
            <span className="text-lg">{t.id}: {t.name}</span>
            <span className={t.status === "PASSED" ? "text-green-500" : "text-red-500"}>
              [{t.status}]
            </span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default QAApp;
